### ISSUE TITLE
Saran Pengganti Substring

### ISSUE THREAD

**Issue by rochmanlj** [dhanyn10/rename-multiple-file#1]
Mungkin bisa digunakan
1. Pilih huruf ke
2. rename word from
3. word from
nanti di labelnya di kasih number of charakter

hanya saran mas makasih keren APPnya

**Comment by dhanyn10** [comment]
belum jelas, substring diganti apa? juga start(index) dan end(index) diganti apa?

**Comment by dhanyn10** [comment]
pembaruan karena fungsi substring yang rasanya tidak terlalu dibutuhkan jadi disimpulkan dihapus saja. terimakasih 😄 
aplikasi saat ini dikembangkan lagi melalui repository berbeda, silahkan kunjungi [multiple file manager](https://github.com/dhanyn10/multiple-file-manager.git)
